import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import GMAIL_ADDRESS, GMAIL_APP_PASSWORD, DIGEST_EMAIL_TO

SECTION_COLORS = {
    "technology": "#5B8DEF",
    "business": "#4CAF82",
    "world": "#E07B5A",
    "opinion": "#9B7ED0",
    "science": "#D4A843",
    "health": "#4DB8A0",
    "sports": "#D08B5B",
    "arts": "#C07ABF",
}


MAX_PER_SECTION = 5


def build_html(summaries_by_section, diff_text, date_str):
    """Build a styled HTML email body matching the web UI palette."""
    articles_html = ""
    for section, articles in summaries_by_section.items():
        color = SECTION_COLORS.get(section, "#C5623A")
        articles_html += (
            f'<tr><td style="padding:24px 0 8px 0;">'
            f'<span style="display:inline-block;width:8px;height:8px;'
            f'border-radius:50%;background:{color};margin-right:8px;'
            f'vertical-align:middle;"></span>'
            f'<span style="font-size:12px;font-weight:700;text-transform:uppercase;'
            f'letter-spacing:0.1em;color:{color};">{section}</span>'
            f'<span style="color:#9B9490;font-size:11px;margin-left:6px;">'
            f'{len(articles)} articles</span>'
            f'</td></tr>'
        )
        top = articles[:MAX_PER_SECTION]
        rest = articles[MAX_PER_SECTION:]
        for a in top:
            articles_html += (
                f'<tr><td style="padding:8px 0 8px 16px;">'
                f'<a href="{a["url"]}" style="color:#2D2B28;font-size:15px;'
                f'font-weight:600;text-decoration:none;">{a["title"]} &#8599;</a>'
                f'<br>'
                f'<span style="color:#6B6560;font-size:13px;line-height:1.6;">'
                f'{a["summary"]}</span>'
                f'</td></tr>'
            )
        if rest:
            articles_html += (
                '<tr><td style="padding:8px 0 4px 16px;">'
                '<span style="font-size:12px;font-weight:600;color:#9B9490;">'
                'Also today:</span></td></tr>'
            )
            for a in rest:
                articles_html += (
                    f'<tr><td style="padding:3px 0 3px 24px;">'
                    f'<a href="{a["url"]}" style="color:#6B6560;font-size:13px;'
                    f'text-decoration:none;">{a["title"]} &#8599;</a>'
                    f'</td></tr>'
                )

    diff_section = ""
    if diff_text:
        diff_lines = diff_text.replace("\n", "<br>")
        diff_section = (
            f'<tr><td style="padding:16px 20px;background:#F5E6DE;'
            f'border-radius:8px;margin-bottom:16px;">'
            f'<strong style="color:#A14520;font-size:14px;">What\'s New</strong>'
            f'<br><span style="color:#6B6560;font-size:13px;line-height:1.7;">'
            f'{diff_lines}</span>'
            f'</td></tr>'
            f'<tr><td style="padding:8px 0;"></td></tr>'
        )

    return f"""\
<html>
<body style="margin:0;padding:0;background:#F5F0E8;font-family:Georgia,serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;">
<tr><td align="center" style="padding:32px 16px;">
<table width="600" cellpadding="0" cellspacing="0"
       style="background:#FFFFFF;border-radius:12px;border:1px solid #E8E0D4;">
  <tr><td style="padding:28px 28px 12px 28px;">
    <h1 style="margin:0;font-size:22px;color:#2D2B28;font-weight:600;">
      News Digest &mdash; {date_str}
    </h1>
  </td></tr>
  <tr><td style="padding:0 28px;">
    <hr style="border:none;border-top:1px solid #E8E0D4;margin:8px 0 4px 0;">
  </td></tr>
  <tr><td style="padding:0 28px;">
    <table width="100%" cellpadding="0" cellspacing="0">
      {diff_section}
      {articles_html}
    </table>
  </td></tr>
  <tr><td style="padding:20px 28px;text-align:center;">
    <span style="color:#9B9490;font-size:11px;">
      Generated by News Digest
    </span>
  </td></tr>
</table>
</td></tr>
</table>
</body>
</html>"""


def send_digest(html, date_str):
    """Send the HTML digest email via Gmail SMTP."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"News Digest — {date_str}"
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = DIGEST_EMAIL_TO
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=30) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_ADDRESS, DIGEST_EMAIL_TO, msg.as_string())

    logging.info(f"Digest email sent to {DIGEST_EMAIL_TO}")
