import logging
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import GMAIL_ADDRESS, GMAIL_APP_PASSWORD, DIGEST_EMAIL_TO

SECTION_COLORS = {
    "technology": "#5B8DEF",
    "business": "#4CAF82",
    "world": "#E07B5A",
    "opinion": "#9B7ED0",
    "science": "#D4A843",
    "health": "#4DB8A0",
    "sports": "#D08B5B",
    "arts": "#C07ABF",
}


MAX_PER_SECTION = 5


def _friendly_date(date_str):
    """Convert '2026-03-21' to '21st March'."""
    dt = datetime.strptime(date_str, "%Y-%m-%d")
    day = dt.day
    if 11 <= day <= 13:
        suffix = "th"
    else:
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th")
    return f"{day}{suffix} {dt.strftime('%B')}"


def build_html(articles_by_section, date_str):
    """Build a styled HTML email body matching the web UI palette."""
    display_date = _friendly_date(date_str)
    articles_html = ""
    for section, articles in articles_by_section.items():
        color = SECTION_COLORS.get(section, "#C5623A")
        # Sort by priority within section
        sorted_articles = sorted(articles, key=lambda a: a.get("priority", 3), reverse=True)
        articles_html += (
            f'<tr><td style="padding:24px 0 8px 0;">'
            f'<span style="display:inline-block;width:8px;height:8px;'
            f'border-radius:50%;background:{color};margin-right:8px;'
            f'vertical-align:middle;"></span>'
            f'<span style="font-size:12px;font-weight:700;text-transform:uppercase;'
            f'letter-spacing:0.1em;color:{color};">{section}</span>'
            f'<span style="color:#9B9490;font-size:11px;margin-left:6px;">'
            f'{len(articles)} articles</span>'
            f'</td></tr>'
        )
        top = sorted_articles[:MAX_PER_SECTION]
        rest = sorted_articles[MAX_PER_SECTION:]
        for a in top:
            tags = a.get("tags", [])
            tag_html = ""
            if tags:
                tag_html = '<br>' + ' '.join(
                    f'<span style="display:inline-block;font-size:10px;color:#6B6560;'
                    f'background:#F5F0E8;border-radius:4px;padding:1px 6px;margin-right:4px;">'
                    f'{t}</span>' for t in tags
                )
            articles_html += (
                f'<tr><td style="padding:4px 0 4px 16px;">'
                f'<a href="{a["url"]}" style="color:#2D2B28;font-size:14px;'
                f'font-weight:600;text-decoration:none;">{a["title"]} &#8599;</a>'
                f'{tag_html}'
                f'</td></tr>'
            )
        if rest:
            articles_html += (
                '<tr><td style="padding:8px 0 4px 16px;">'
                '<span style="font-size:12px;font-weight:600;color:#9B9490;">'
                'Also today:</span></td></tr>'
            )
            for a in rest:
                articles_html += (
                    f'<tr><td style="padding:3px 0 3px 24px;">'
                    f'<a href="{a["url"]}" style="color:#6B6560;font-size:13px;'
                    f'text-decoration:none;">{a["title"]} &#8599;</a>'
                    f'</td></tr>'
                )

    return f"""\
<html>
<body style="margin:0;padding:0;background:#F5F0E8;font-family:Georgia,serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;">
<tr><td align="center" style="padding:32px 16px;">
<table width="600" cellpadding="0" cellspacing="0"
       style="background:#FFFFFF;border-radius:12px;border:1px solid #E8E0D4;">
  <tr><td style="padding:28px 28px 12px 28px;">
    <h1 style="margin:0;font-size:22px;color:#2D2B28;font-weight:600;">
      News Digest &mdash; {display_date}
    </h1>
  </td></tr>
  <tr><td style="padding:0 28px;">
    <hr style="border:none;border-top:1px solid #E8E0D4;margin:8px 0 4px 0;">
  </td></tr>
  <tr><td style="padding:0 28px;">
    <table width="100%" cellpadding="0" cellspacing="0">
      {articles_html}
    </table>
  </td></tr>
  <tr><td style="padding:20px 28px;text-align:center;">
    <span style="color:#9B9490;font-size:11px;">
      Generated by News Digest
    </span>
  </td></tr>
</table>
</td></tr>
</table>
</body>
</html>"""


def send_digest(html, date_str):
    """Send the HTML digest email via Gmail SMTP."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"News Digest — {_friendly_date(date_str)}"
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = DIGEST_EMAIL_TO
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=30) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_ADDRESS, DIGEST_EMAIL_TO, msg.as_string())

    logging.info(f"Digest email sent to {DIGEST_EMAIL_TO}")
